### ISSUE TITLE
Provide Steps Breakdown by Date

### ISSUE THREAD

**Issue by AndreyBakharev** [uncheckederror/Ocean2Ocean#10]
Would be great to have a breakdown of steps by date for various users :)

**Comment by uncheckederror** [comment]
I am imagining this as a line chart where the x-axis is the date and the y-axis is the daily step count.

It would look similar to [this example.](https://www.chartjs.org/samples/latest/charts/line/basic.html)

Does that sound right to you @AndreyBakharev ?

**Comment by AndreyBakharev** [comment]
That sounds great I was just thinking a column on the table of data, but graphical is even better :)

**Comment by uncheckederror** [comment]
I have added charts that show steps by date in two places.

1. When you submit your steps for the day you will now see a chart showing the steps you've submitted for the last 14 days.
2. On the leaderboard there is now a chart that shows the steps submitted by date for the whole journey.

These changes are now live.

You can check out the [new leaderboard here.](https://ocean2ocean.azurewebsites.net/Home/Leaderboard/KCIT)

And then submit some steps to see the new chart on the submissions page.

**Comment by uncheckederror** [comment]
In 1e717ba I updated the graphs to improve the display of data even when there is only a single data point supplied.
