### ISSUE TITLE
Allow for Nicknames to be a selected team

### ISSUE THREAD

**Issue by sandyrav** [uncheckederror/Ocean2Ocean#12]
When we move to an enterprise wide application, we should allow for nicknames to be selected from a dropdown so we can allow for team to team competitions.

**Comment by uncheckederror** [comment]
I am imagining this a drop down below the Journey name where you can select a team.

**Comment by uncheckederror** [comment]
In 7eb237a and ec2abfe I modified the table structure of the app and the data access library to support the concept of a team name in preparation for adding it to the app.

**Comment by uncheckederror** [comment]
I have added teams to the app. They are the children of Journeys and the parents of Nicknames. If you don't submit a team along with your nickname it will use the default team, which is the name of the journey. 

To make this more useful we need to:

- [x] Group nicknames by teams on the leaderboard page.

- [x] Allow the selection of a team on the map page with a drop down.

- [x] Allow the modification of journeys, teams, and nicknames by users.

**Comment by uncheckederror** [comment]
@sandyrav You can check out the new teams drop down here: https://ocean2ocean.azurewebsites.net/SE%20Walk%20Across%20America

And the new leaderboard where steps are broken out by teams here: https://ocean2ocean.azurewebsites.net/SE%20Walk%20Across%20America/Leaderboard

These changes and the new database table structure that supports them should enable us to scale this application out to the rest of the enterprise.
